syntax on
set nocompatible
set showmatch
set incsearch
set hlsearch
set path+=**
set lazyredraw
set showcmd

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set number
set relativenumber

filetype plugin indent on
set autoindent

" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

if (empty($TMUX))
    if (has("termguicolors"))
        set termguicolors
    endif
endif
colorscheme onedark

inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O
noremap <F5> :!Compile %<CR>
" nnoremap <silent> <ESC> :noh<CR><ESC>

command CP :r ~/.vim/snippets/competitive.cpp
