#! /bin/bash

. ~/.scripts/rofi_lib

option=$(rofiQuery Homework $'Algem\nCalculus')

if [[ $option == "Algem" ]]; then
    zathura ~/Documents/textbooks/Algem2022.pdf &
    zathura ~/Documents/textbooks/Algem-Tasks.djvu &
elif [[ $option == "Calculus" ]]; then
    zathura ~/Documents/textbooks/Calculus2022.pdf &
    zathura ~/Documents/textbooks/Calculus-Tasks.djvu &
fi
