#! /bin/bash

. ~/.scripts/rofi_lib

res=$(rofiQuery Redshift "Day (5000)\\nNight (3250)\\nReset\\nOr type in the number.")
case ${res} in
    "Day (5000)")
        redshift -x
        redshift -O 5000
        ;;
    "Night (3250)")
        redshift -x
        redshift -O 3250
        ;;
    "Reset")
        ;;
    "")
        ;;
    *)
        redshift -x
        redshift -O ${res}
        ;;
esac
