#! /bin/bash

query() {
    res=$(echo -e "$1" | rofi -dmenu -p "Redshift" -lines $2 -i)
    echo $res
}

res=$(query "Day (5000)\\nNight (3250)\\nReset\\nOr type in the number.")
redshift -x
case ${res} in
    "Day (5000)")
        redshift -O 5000
        ;;
    "Night (3250)")
        redshift -O 3250
        ;;
    "Reset")
        ;;
    *)
        redshift -O ${res}
        ;;
esac
