#! /bin/bash

word=$(xclip -o)
trans "$word"
read result
if [[ $result == "a" ]]; then
    output=$(trans -s ZH -t ENG -d "$word")
    pinyin=$(echo "$output" | head -n 2 | tail -n 1 | sed -e "s/[()]//g")
    translation=$(echo -e "$output" | head -n 4 | tail -n 1 | tr -d "[1m[22m")
    echo "$word; $translation; $pinyin" >> ~/chinese/auto-words.txt
    vim ~/chinese/auto-words.txt
fi
