#! /bin/bash

. ~/.scripts/rofi_lib

res=$(rofiQuery Shutdown "Off Screen\\nLock Screen\\nShutdown\\nReboot\\nKill Xorg")

case ${res} in
    "Off Screen")
        screen_off
        ;;
    "Lock Screen")
        echo "Maybe it's time to implement it?"
        ;;
    "Shutdown")
        shutdown now
        ;;
    "Reboot")
        reboot
        ;;
    "Kill Xorg")
        killall Xorg
        ;;
    *)
        rofiQuery Shutdown "Invalid Argument: ${res}"
        ;;
esac
