#!/bin/bash

. ~/.scripts/rofi_lib

res=$(rofiQuery VPN "Enable\\nDisable")
case $res in
    "Enable")
        sudo vpn_toggle up
        ;;
    "Disable")
        sudo vpn_toggle down
        ;;
    *)
        rofiQuery VPN "Invalid Input."
        ;;
esac
