#! /bin/bash

word=$(wl-paste -p)
trans "$word"
while true; do
    read -n1 result
    echo
    if [[ $result == "s" ]]; then
        freqColl=$(grep -e "^$word " --max-count=1 ~/chinese/freq-coll-v2 | awk '{print $2}')
        freqLit=$(grep -e "^$word " --max-count=1 ~/chinese/freq-lit-v2 | awk '{print $2}')
        echo "Coll: $freqColl, Lit: $freqLit"
    elif [[ $result == "a" ]]; then
        output=$(trans -s ZH -t ENG -d "$word")
        pinyin=$(echo "$output" | head -n 2 | tail -n 1 | sed -e "s/[()]//g")
        translation=$(echo -e "$output" | head -n 4 | tail -n 1 | tr -d "[1m[22m")
        echo "Sentence?"
        read sentence
        echo "$word; $translation; $pinyin; $sentence" >> ~/chinese/auto-words.txt
        vim ~/chinese/auto-words.txt
        break
    elif [[ $result == "z" ]]; then
        clear
        trans -s ZH -show-original-phonetics Y "$word"
    else
        break
    fi
done
